version: "3.9"
services:
  master:
    image: redis
    container_name: redis-master
    volumes: 
    - /home/docker/redis/redis-master/data:/data
    - /home/docker/redis/conf:/usr/local/etc/redis
    hostname: redis-master
    ports:
    - 6379:6379
    networks:
      redis_network: 
        ipv4_address: 172.18.0.2
    command: redis-server /usr/local/etc/redis/redis.conf
    
  slave1:
    image: redis
    container_name: redis-slave1
    volumes: 
    - /home/docker/redis/redis-slave1/data:/data
    ports:
    - 6380:6379
    networks:
      redis_network: 
        ipv4_address: 172.18.0.3
    command: redis-server --slaveof redis-master 6379
    depends_on: 
    - master

  slave2:
    image: redis
    container_name: redis-slave2
    volumes: 
    - /home/docker/redis/redis-slave2/data:/data
    ports:
    - 6381:6379
    networks:
      redis_network: 
        ipv4_address: 172.18.0.4
    command: redis-server --slaveof redis-master 6379
    depends_on: 
    - master
    - slave1
    
networks:
  redis_network:
    driver: bridge
    ipam: 
      config: 
      - subnet: 172.18.0.0/16